language: node_js
node_js:
    - "node"
env:
  global:
  - CC_TEST_REPOTER_ID=4689ee4d5800bef59dd38644bf9fd9a6da6d9d5c125cc94e7d4745ad581c2817
cache:
  directories:
   - "node_modules"
services:
 - postgresql
addons:
  chrome: stable
  postgresql: "9.6"
before_script:
  - npm install mocha-lcov-reporter --save-dev
  - npm install supertest 
  - psql -c 'create database MyDairy;' -U postgres
  - npm run migrate
  - curl -L https://codeclimate.com/downloads/test-reporter-latest-linux-amd64 >  ./cc-test-reporter
  - chmod +x ./cc-test reporter
after_script:
 - /cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coverage
  - npm install codeclimate-test-reporter
  - codeclimat-test-reporter < coverage/lcov.info
